--- 
- name: Install Common
  hosts: all
  tags: common
  roles: 
  - common

- name: Configure mdm
  hosts: mdm
  tags: mdm
  roles:
  - mdm

- name: Configure tb
  tags: tb
  hosts: tb
  roles:
  - tb

- name: Configure sds
  tags: sds
  hosts: sds
  roles:
  - sds

- name: Configure callhome
  tags: callhome
  hosts: callhome
  roles:
  - callhome

- name: Configure sdc
  tags: sdc
  hosts: sdc
  roles:
  - sdc

- name: Configure Gateway
  hosts: gateway
  tags: gateway
  roles:
  - gateway

- name: Configure openstack-controllers
  tags: openstack-controllers
  hosts: openstack-controllers
  roles:
  - openstack-controllers

- name: Configure openstack-compute
  tags: openstack-compute
  hosts: openstack-compute
  roles:
  - openstack-compute
