--- 
- name:  set up facts
  hosts: all
  tags: common 
  tasks:
  - set_fact: scaleio_mdm_headnode_ip="{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    run_once: true
  - set_fact: scaleio_mdm_secondary_ip="{{ hostvars[groups['mdm'][1]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    run_once: true

- name: Install Common
  hosts: all
  tags: common
  roles: 
  - common
# Installing lia seems to break mdm connections, not sure why, leaving disabled for now.
#  - lia

- name: Configure mdm
  hosts: mdm
  tags: mdm
  roles:
  - mdm

- name: Configure tb
  tags: tb
  hosts: tb
  roles:
  - tb

- name: Configure Gateway
  hosts: gateway
  tags: gateway
  roles:
  - gateway

- name: Configure sds
  tags: sds
  hosts: sds
  roles:
  - sds

- name: Configure callhome
  tags: callhome
  hosts: callhome
  roles:
  - callhome

- name: Configure sdc
  tags: sdc
  hosts: sdc
  roles:
  - sdc

- name: Configure openstack-controllers
  tags: openstack-controllers
  hosts: openstack-controllers
  roles:
  - openstack-controllers

- name: Configure openstack-compute
  tags: openstack-compute
  hosts: openstack-compute
  roles:
  - openstack-compute
