---
- name: Current Python version
  command: python -c 'import sys; print "%s.%s" % (sys.version_info.major, sys.version_info.minor)'
  register: version
  changed_when: false

- name: Copy libvirt driver
  copy:
    src: "{{ scaleio_libvirt_driver }}"
    dest: "/usr/lib/python{{ version.stdout }}/site-packages/nova/virt/libvirt/"

- name: Copy ScaleIO Filters
  copy:
    src: "{{ scaleio_nova_filters }}"
    dest: /etc/nova/rootwrap.d/

- name: Modify Nova to include ScaleIO driver
  ini_file:
    dest: /etc/nova/nova.conf
    section: libvirt
    option: volume_drivers
    value: "{{ nova_volume_drivers }}"
    backup: true
  register: nova

- name: restart openstack-nova-compute
  service:
    name: openstack-nova-compute
    state: restarted
  when: nova|changed
