scaleio_license:

scaleio_mgmt_interface: em3 
scaleio_interface: bond0.1803

scaleio_base_package_name: EMC-ScaleIO
scaleio_version: 1.32-402.1
scaleio_protection_domain: pd1
scaleio_cluster_mode: true
scaleio_cluster_name: cluster1
scaleio_password: Cluster1!
scaleio_gateway_admin_password: 'Cluster1!'
scaleio_lia_token: 'Cluster1!'
scaleio_storage_pool: default

scaleio_gateway_port: 8081
scaleio_gateway_ssl_port: 8443

scaleio_callhome_config:
    - { section: 'general', option: 'email_from', value: 'from@somewhere.com' }
    - { section: 'general', option: 'username', value: '' }
    - { section: 'general', option: 'password', value: '' }
    - { section: 'general', option: 'customer_name', value: 'somewhere' }
    - { section: 'smtp', option: 'host', value: '127.0.0.1' }
    - { section: 'smtp', option: 'username', value: '' }
    - { section: 'smtp', option: 'password', value: '' }
    - { section: 'email_alert', option: 'email_to', value: 'to@somewhere.com' }
    - { section: 'email_alert', option: 'severity', value: '' }


scaleio_mdm_primary_ip: "{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
scaleio_mdm_primary_mgmt_ip: "{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_mgmt_interface]['ipv4']['address'] }}" 

scaleio_mdm_secondary_ip: "{{ hostvars[groups['mdm'][1]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
scaleio_mdm_secondary_mgmt_ip: "{{ hostvars[groups['mdm'][1]]['ansible_'+scaleio_mgmt_interface]['ipv4']['address'] }}"

# This IP address is either a single system or a VIP for HAproxy e.g. in OpenStack 
scaleio_gateway_ip: 172.17.17.112 

scaleio_tb_ip: "{{ hostvars[groups['tb'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"



