---
# handlers file for openstack-controllers
#

- name: pacemaker disable cinder-api
  command: pcs resource disable cinder-api --wait 30
  run_once: true
  notify: pacemaker enable cinder-api
  when: use_pacemaker

- name: pacemaker enable cinder-api
  command: pcs resource enable cinder-api --wait 30
  run_once: true
  when: use_pacemaker
